global.authUserID = "";
global.authUserRef = "";
global.authUser = "";
global.authUserProfilePic = "https://i.imgur.com/3bOE2E6.jpeg";
global.defaultProfilePic = "./images/user.png";
global.authName = "";
global.authLastName = "";
("https://www.business2community.com/wp-content/uploads/2017/08/blank-profile-picture-973460_640.png");
global.notificationList = [];
global.MSuser={};
global.authEmail = "";
global.eventData=[{}];
global.showEvent=false;
global.notificationId=0;